### ISSUE TITLE
Cannot read property 'trigger' of null

### ISSUE THREAD

**Issue by TomWq** [wuba/react-native-echarts#92] opened 2023-07-28 09:30 UTC
我在使用过程中多点几次就会出现这个错误: Cannot read property 'trigger' of null
"react-native":" 0.72.3"
 "echarts": "^5.4.3",
 "@wuba/react-native-echarts": "^1.2.2"

**Comment by zhiqingchen** [comment] 2023-07-28 10:08
有相应demo吗

**Comment by hzlgit** [comment] 2023-08-06 10:46
我也是，重进几次就出现了，安卓的

**Comment by hzlgit** [comment] 2023-08-07 00:54
好像是因为增加了dataZoom的缘故，其它没加的倒是没触发过这个错误

**Comment by zhiqingchen** [comment] 2023-08-07 02:37
重进几次就出现了，指的是使用 react navigation 跳转页面吗

**Comment by zhiqingchen** [comment] 2023-08-18 11:24
try 1.2.3-alpha.0

**Comment by wogno** [comment] 2023-08-19 12:32
@zhiqingchen The issue is still there on android but not on ios

![Screenshot_1692448294](https://github.com/wuba/react-native-echarts/assets/31076843/f9a607a2-0522-4f3f-bb7a-1ec2a9a1bd23)

**Comment by iambool** [comment] 2023-08-22 08:34
Any other demos? I don't get errors in the above case

**Comment by aleksey-mukho** [comment] 2023-08-23 13:37
I reproduced on iOS

**Comment by zhiqingchen** [comment] 2023-08-23 15:02
How

**Comment by pavelbabenko** [comment] 2023-08-24 18:05
Same issue on iOS
![image](https://github.com/wuba/react-native-echarts/assets/44643721/4f64b892-ff16-4f7b-aba8-de1e695372d7)

**Comment by wogno** [comment] 2023-08-29 19:32
Hi, someone has found a solution?

**Comment by zhiqingchen** [comment] 2023-08-30 00:38
Can anyone provide a reproducible demo of the

**Comment by hazirmagron** [comment] 2023-09-14 22:12
Any solution? I have started to receive this error message as well.

**Comment by hazirmagron** [comment] 2023-09-16 09:44
Do you have a suggestion of what might cause this? The bug is app breaking and I'm suspecting it has to do with version incompatibility since I never experienced it in the past using very similar code. It also happens seemingly randomly @zhiqingchen

**Comment by zhiqingchen** [comment] 2023-09-16 10:32
I haven't been able to reproduce this

**Comment by zhiqingchen** [comment] 2023-09-16 10:43
try 1.1.2

**Comment by hazirmagron** [comment] 2023-09-16 10:47
> try 1.1.2

Tried - issue remains unfortunately

**Comment by zhiqingchen** [comment] 2023-09-18 06:38
If someone can reproduce the issue, can provide a expo snack so that we can easily locate and fix it.

https://snack.expo.dev/

**Comment by wogno** [comment] 2023-10-01 08:38
I fixed this issue with a temporary config in node_modules, after many tests I saw this error just appeared when the user clicks on any time of my picker calendar, to filter dates, when action is too quick this error appears, but when is slower error did not appear.


So, I did use not the recommendation method to fix the issue but checked if the element existed before the call method.

Step 1, go on zrender on your node_modules and go on zrender.js on lib

all call method should predifined by method && method(), exemple this.animation.start() become this.animation && this.animation.start()

This correction is based on @yechunxi 

My files new zrender js file

**Comment by wogno** [comment] 2023-10-01 08:38
/*!
* ZRender, a high performance 2d drawing library.
*
* Copyright (c) 2013, Baidu Inc.
* All rights reserved.
*
* LICENSE
* https://github.com/ecomfe/zrender/blob/master/LICENSE.txt
*/
import env from './core/env.js';
import * as zrUtil from './core/util.js';
import Handler from './Handler.js';
import Storage from './Storage.js';
import Animation, { getTime } from './animation/Animation.js';
import HandlerProxy from './dom/HandlerProxy.js';
import { lum } from './tool/color.js';
import { DARK_MODE_THRESHOLD } from './config.js';
import Group from './graphic/Group.js';
var painterCtors = {};
var instances = {};
function delInstance(id) {
    delete instances[id];
}
function isDarkMode(backgroundColor) {
    if (!backgroundColor) {
        return false;
    }
    if (typeof backgroundColor === 'string') {
        return lum(backgroundColor, 1) < DARK_MODE_THRESHOLD;
    }
    else if (backgroundColor.colorStops) {
        var colorStops = backgroundColor.colorStops;
        var totalLum = 0;
        var len = colorStops.length;
        for (var i = 0; i < len; i++) {
            totalLum += lum(colorStops[i].color, 1);
        }
        totalLum /= len;
        return totalLum < DARK_MODE_THRESHOLD;
    }
    return false;
}
var ZRender = (function () {
    function ZRender(id, dom, opts) {
        var _this = this;
        this._sleepAfterStill = 10;
        this._stillFrameAccum = 0;
        this._needsRefresh = true;
        this._needsRefreshHover = true;
        this._darkMode = false;
        opts = opts || {};
        this.dom = dom;
        this.id = id;
        var storage = new Storage();
        var rendererType = opts.renderer || 'canvas';
        if (!painterCtors[rendererType]) {
            rendererType = zrUtil.keys(painterCtors)[0];
        }
        if (process.env.NODE_ENV !== 'production') {
            if (!painterCtors[rendererType]) {
                throw new Error("Renderer '" + rendererType + "' is not imported. Please import it first.");
            }
        }
        opts.useDirtyRect = opts.useDirtyRect == null
            ? false
            : opts.useDirtyRect;
        var painter = new painterCtors[rendererType](dom, storage, opts, id);
        var ssrMode = opts.ssr || painter.ssrOnly;
        this.storage = storage;
        this.painter = painter;
        var handerProxy = (!env.node && !env.worker && !ssrMode)
            ? new HandlerProxy(painter.getViewportRoot(), painter.root)
            : null;
        var useCoarsePointer = opts.useCoarsePointer;
        var usePointerSize = (useCoarsePointer == null || useCoarsePointer === 'auto')
            ? env.touchEventsSupported
            : !!useCoarsePointer;
        var defaultPointerSize = 44;
        var pointerSize;
        if (usePointerSize) {
            pointerSize = zrUtil.retrieve2(opts.pointerSize, defaultPointerSize);
        }
        this.handler = new Handler(storage, painter, handerProxy, painter.root, pointerSize);
        this.animation = new Animation({
            stage: {
                update: ssrMode ? null : function () { return _this._flush(true); }
            }
        });
        if (!ssrMode) {
            this.animation.start();
        }
    }
    ZRender.prototype.add = function (el) {
        if (!el) {
            return;
        }
        this.storage && this.storage.addRoot(el);
        el.addSelfToZr(this);
        this.refresh();
    };
    ZRender.prototype.remove = function (el) {
        if (!el) {
            return;
        }
        this.storage && this.storage.delRoot(el);
        el.removeSelfFromZr(this);
        this.refresh();
    };
    ZRender.prototype.configLayer = function (zLevel, config) {
        if (this.painter.configLayer) {
            this.painter.configLayer(zLevel, config);
        }
        this.refresh();
    };
    ZRender.prototype.setBackgroundColor = function (backgroundColor) {
        if (this.painter.setBackgroundColor) {
            this.painter.setBackgroundColor(backgroundColor);
        }
        this.refresh();
        this._backgroundColor = backgroundColor;
        this._darkMode = isDarkMode(backgroundColor);
    };
    ZRender.prototype.getBackgroundColor = function () {
        return this._backgroundColor;
    };
    ZRender.prototype.setDarkMode = function (darkMode) {
        this._darkMode = darkMode;
    };
    ZRender.prototype.isDarkMode = function () {
        return this._darkMode;
    };
    ZRender.prototype.refreshImmediately = function (fromInside) {
        if (!fromInside) {
            this.animation && this.animation.update(true);
        }
        this._needsRefresh = false;
        this.painter.refresh();
        this._needsRefresh = false;
    };
    ZRender.prototype.refresh = function () {
        this._needsRefresh = true;
        this.animation && this.animation.start();
    };
    ZRender.prototype.flush = function () {
        this._flush(false);
    };
    ZRender.prototype._flush = function (fromInside) {
        var triggerRendered;
        var start = getTime();
        if (this._needsRefresh) {
            triggerRendered = true;
            this.refreshImmediately(fromInside);
        }
        if (this._needsRefreshHover) {
            triggerRendered = true;
            this.refreshHoverImmediately();
        }
        var end = getTime();
        if (triggerRendered) {
            this._stillFrameAccum = 0;
            this.trigger('rendered', {
                elapsedTime: end - start
            });
        }
        else if (this._sleepAfterStill > 0) {
            this._stillFrameAccum++;
            if (this._stillFrameAccum > this._sleepAfterStill) {
                this.animation && this.animation.stop();
            }
        }
    };
    ZRender.prototype.setSleepAfterStill = function (stillFramesCount) {
        this._sleepAfterStill = stillFramesCount;
    };
    ZRender.prototype.wakeUp = function () {
        this.animation && this.animation.start();
        this._stillFrameAccum = 0;
    };
    ZRender.prototype.refreshHover = function () {
        this._needsRefreshHover = true;
    };
    ZRender.prototype.refreshHoverImmediately = function () {
        this._needsRefreshHover = false;
        if (this.painter.refreshHover && this.painter.getType() === 'canvas') {
            this.painter.refreshHover();
        }
    };
    ZRender.prototype.resize = function (opts) {
        opts = opts || {};
        this.painter.resize(opts.width, opts.height);
        this.handler.resize();
    };
    ZRender.prototype.clearAnimation = function () {
        this.animation && this.animation.clear();
    };
    ZRender.prototype.getWidth = function () {
        return this.painter.getWidth();
    };
    ZRender.prototype.getHeight = function () {
        return this.painter.getHeight();
    };
    ZRender.prototype.setCursorStyle = function (cursorStyle) {
        this.handler.setCursorStyle(cursorStyle);
    };
    ZRender.prototype.findHover = function (x, y) {
        return this.handler.findHover(x, y);
    };
    ZRender.prototype.on = function (eventName, eventHandler, context) {
        this.handler.on(eventName, eventHandler, context);
        return this;
    };
    ZRender.prototype.off = function (eventName, eventHandler) {
        this.handler.off(eventName, eventHandler);
    };
    ZRender.prototype.trigger = function (eventName, event) {
        this?.handler?.trigger(eventName, event);
    };
    ZRender.prototype.clear = function () {
        var roots = this.storage.getRoots();
        for (var i = 0; i < roots.length; i++) {
            if (roots[i] instanceof Group) {
                roots[i].removeSelfFromZr(this);
            }
        }
        this.storage.delAllRoots();
        this.painter.clear();
    };
    ZRender.prototype.dispose = function () {
        this.animation && this.animation.stop();
        this.clear();
        this.storage && this.storage.dispose();
        this.painter && this.painter.dispose();
        this.handler && this.handler.dispose();
        this.animation =
            this.storage =
                this.painter =
                    this.handler = null;
        delInstance(this.id);
    };
    return ZRender;
}());
export function init(dom, opts) {
    var zr = new ZRender(zrUtil.guid(), dom, opts);
    instances[zr.id] = zr;
    return zr;
}
export function dispose(zr) {
    zr.dispose();
}
export function disposeAll() {
    for (var key in instances) {
        if (instances.hasOwnProperty(key)) {
            instances[key].dispose();
        }
    }
    instances = {};
}
export function getInstance(id) {
    return instances[id];
}
export function registerPainter(name, Ctor) {
    painterCtors[name] = Ctor;
}
export var version = '5.4.4';
;

**Comment by lucaswitch** [comment] 2023-10-05 22:26
Having this error on Android 12.

**Comment by lucaswitch** [comment] 2023-10-05 22:32
![Screenshot_2023-10-05-19-29-28-700_com fusion](https://github.com/wuba/react-native-echarts/assets/29023475/4f1499f2-22f1-4746-a6bc-f89748f7d51f)
It's happening in this line when the chart updates 3,4 times in a small space of time.

**Comment by yechunxi** [comment] 2023-10-10 06:47
I reproduce the issue, The reason for this problem is that after the chart executes dispose, some instances are set to empty, but some internal asynchronous operations will be called again, resulting in an error.

The current temporary solution is to apply a patch to zrender.js to determine before the method is called.  same as @wogno w

 I gave zrender a PR, but it has not been officially verified and merged. If anyone has a better solution, welcome to submit a PR.

**Comment by krmao** [comment] 2023-10-10 08:27
![image](https://github.com/wuba/react-native-echarts/assets/7344437/267a793f-2b2d-4896-9a55-afc29fea43ed)

same issue after slowly click legend on android,  but ios is ok

```
 ERROR  TypeError: Cannot read property 'trigger' of null, js engine: hermes
```

**Comment by alecsloan** [comment] 2023-10-13 03:44
It looks like removing `return () => chart?.dispose()` fixed this issue for me. Removing this also gave my charts a bit better performance it seems.

@krmao You could probably fix that warning by trying to get the chart instance by ref, this is what I have:

```javascript
      chart = echarts.getInstanceByDom(chartRef.current) || echarts.init(chartRef.current,'light', {
        height: height,
        width: width,
        renderer: 'svg',
      });
```

**Comment by krmao** [comment] 2023-10-16 06:32
> It looks like removing `return () => chart?.dispose()` fixed this issue for me. Removing this also gave my charts a bit better performance it seems.
> 
> @krmao You could probably fix that warning by trying to get the chart instance by ref, this is what I have:
> 
> ```js
>       chart = echarts.getInstanceByDom(chartRef.current) || echarts.init(chartRef.current,'light', {
>         height: height,
>         width: width,
>         renderer: 'svg',
>       });
> ```

yes, my final code is here, for some echarts dispose manually

```
    if (!chartInstance.current || chartInstance.current.isDisposed()) {
            chartInstance.current = echarts.init(innerChartRef.current, 'light', {
              renderer: 'svg',
              width,
              height,
            });
      }
```

**Comment by nguyenvinhhn** [comment] 2023-10-21 03:15
fix:
    
    useEffect(() => {
        setTimeout(() => { // fix
            let chart: any;
            if (chartRef && chartRef.current) {
                // @ts-ignore
                chart = echarts.init(chartRef.current, 'light', {
                    renderer: 'svg',
                    width: E_WIDTH,
                    height: E_HEIGHT,
                });
                chart.setOption(option);
            }
            return () => chart?.dispose();
        }, 1)
    }, [option]);

**Comment by wogno** [comment] 2023-11-27 22:22
Zrender is too slow, to fix bugs, can we change the render library?

**Comment by zhiqingchen** [comment] 2023-11-28 03:43
Not yet, zrender is a rendering library for echarts, so if you need a quick fix, patch it in your own project.

**Comment by renishdeveloper** [comment] 2024-01-23 12:52
How to change the zrender with any other alternative ? anyone have any idea than let me know. I also have to change as I'm experiencing slow rendering of chart in my react native application.

**Closed** 2024-02-23 10:16 UTC
Labels: bug
